### ISSUE TITLE
inbo_rapport  + gitbook: cover & colofon

### ISSUE THREAD

**Issue by hansvancalster** [inbo/INBOmd#70]
Currently, the following in YAML header will, when rendered, show title, author names and doi number on the first page if no image is given to cover-image, or, show the cover image instead (which will look like cover of INBO pdf reports).

```
title: "title"
author: "name"
reportnr: "doi:..."
cover-image: "image.png"
output:
  bookdown::gitbook:
    split_by: chapter+number
    split_bib: FALSE
    template: !expr INBOmd::inbo_rapport_css("html")
```

The request is to allow cover and colofon info to be part of the html template. Some ideas (took them from e-mail discussion):

- add relevant (page number is not relevant) colofon info as information at the bottom of each page or as sidebar information (@ElsLommelen )
- relevant info can also include: date when last updated, version number (@ElsLommelen )
- add a "suggested citation" section in the side bar as well, maybe hidden behind a button (@ElsLommelen )
- add cover image as a small (thumbnail?) version to the colofon section (@florisvdh )

Maybe something to consider in 2021.
